name: Build, Tag & Deploy Mod

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # When a tag is pushed, update gradle.properties so that mod_version matches the tag.
      - name: Update mod_version from Tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Extract version number (remove leading 'v')
          version=${GITHUB_REF_NAME#v}
          echo "Tag version: $version"
          # Update the mod_version property in gradle.properties
          sed -i "s/^mod_version=.*/mod_version=${version}/" gradle.properties
          echo "Updated gradle.properties:"
          cat gradle.properties

      - name: Build Mod
        run: ./gradlew build

  tag_release:
    runs-on: ubuntu-latest
    needs: build
    # Only run this job on pushes to the main branch (not on tag pushes)
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code for Tagging
        uses: actions/checkout@v3

      # Use an auto-tagging action to create a new tag.
      - name: Auto Tag Release
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Run the deploy job only when a tag is pushed.
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout Code for Deployment
        uses: actions/checkout@v3

      - name: Publish to Modrinth via Minotaur
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
