name: Build and Release Minecraft Mod

on:
  push:
    tags:
      - 'v*'  # Runs when pushing a tag like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build the mod
        run: ./gradlew build

      - name: Upload Mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: The-Fallen-Mod
          path: build/libs/the-fallen-*.jar  # Uploads all matching versions

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v3
        with:
          name: The-Fallen-Mod
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/the-fallen-*.jar
          body: "Automated release of The Fallen Mod."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
