permissions:
  contents: write

name: Deploy on Release Workflow Completion

on:
  workflow_run:
    workflows: ["Build & Tag on Main Branch"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code for Deployment
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Get Latest Tag and Version
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $tag"
          # Remove a leading "v" if it exists
          version=${tag#v}
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: "Release ${{ steps.get_tag.outputs.tag }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/the-fallen-${{ steps.get_tag.outputs.version }}.jar
          asset_name: "the-fallen-${{ steps.get_tag.outputs.version }}.jar"
          asset_content_type: application/java-archive

      - name: Publish to Modrinth via Minotaur
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}