permissions:
  contents: write

name: Build & Tag on Main Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Mod
        run: ./gradlew build

  tag_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code for Tagging
        uses: actions/checkout@v3

      - name: Read mod_version from gradle.properties
        id: read_version
        run: |
          version=$(grep "^mod_version=" gradle.properties | cut -d'=' -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "mod_version: $version"
          
      - name: Auto Tag Release
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: "v${{ steps.read_version.outputs.version }}"