permissions:
  contents: write

name: Update Version, Build & Tag Release

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip version update]') }}
    outputs:
      new_version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Bump mod_version in gradle.properties
        id: bump_version
        run: |
          current_version=$(grep "^mod_version=" gradle.properties | cut -d'=' -f2)
          echo "Current mod_version: $current_version"
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "New version will be: $new_version"
          # For Linux; on macOS use: sed -i '' "s/^mod_version=.*/mod_version=${new_version}/" gradle.properties
          sed -i "s/^mod_version=.*/mod_version=${new_version}/" gradle.properties
          echo "Updated gradle.properties:"
          cat gradle.properties
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT

      - name: Commit and Push version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gradle.properties
          git commit -m "Bump mod_version to ${{ steps.bump_version.outputs.new_version }} [skip version update]"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/declanhuggins/the-fallen.git
          git push origin HEAD:${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    needs: update_version
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Mod
        run: ./gradlew build

  tag_release:
    runs-on: ubuntu-latest
    needs: [build, update_version]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code for Tagging
        uses: actions/checkout@v3

      - name: Auto Tag Release
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: "v${{ needs.update_version.outputs.new_version }}"